
name: publish_daily # workflow name
on: # trigger
  schedule:
    - cron: '* 11 * * *'
  push:
    branches: [ master ]

# parallel jobs to perform
jobs:
  # === unittest execution ===
  unittest:
    runs-on: ubuntu-latest # runner
    
    steps: # tasks  
    - name: Set Github Workspace # access Github Workspace
      uses: actions/checkout@v2
    - name: Set up Python 3.x # set architecture and Python3
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64' # architecture

    - name: Install dependencies # dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Export month # run unittests
      run:
        python -c 'import covid19poland as PL; PL.export_month()'

    - name: Commit files # transfer the new html files back into the repository
      run: |
        git config --local user.name "publish_daily"
        git add data/*
        git commit -m "Automatic daily update"
    - name: Push changes # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.DAILY_PUBLIC_KEY }}
        force: true